name: Test, Lint and Deploy
on: push

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading the Code
        uses: actions/checkout@v3.5.2

      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing Dependencies
        run: npm ci

      - name: running tests
        run: npm run test

      - name: Printing Message
        run: echo "Testing Completed Successfully"
  
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading the Code
        uses: actions/checkout@v3.5.2
      
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing Dependencies
        run: npm ci

      - name: Running Linter
        run: npm run lint
      
      - name: Printing Message
        run: echo "Linting Completed Successfully"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Downloading the code
        uses: actions/checkout@v3.5.2
      
      - name: Installing NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Installing Dependencies
        run: npm ci

      - name: Building the code
        run: npm run build

      - name: Printing Message
        run: echo "Deployed Successfully"
    